// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5lo4pAVNEsJdliq5RdFEcMhcLQBCcEA4',
    appId: '1:978913197408:web:102bdfeba63fc2d5ceb205',
    messagingSenderId: '978913197408',
    projectId: 'fir-chat-app-aabd2',
    authDomain: 'fir-chat-app-aabd2.firebaseapp.com',
    storageBucket: 'fir-chat-app-aabd2.appspot.com',
    measurementId: 'G-XE5602N3YQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXsq95RBbRRJPCK-JCDke4s_YxKzm6_4M',
    appId: '1:978913197408:android:08dc44e54e82934dceb205',
    messagingSenderId: '978913197408',
    projectId: 'fir-chat-app-aabd2',
    storageBucket: 'fir-chat-app-aabd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1CWtH7KxCDdN52dN_NjGiImUZqhVEEUY',
    appId: '1:978913197408:ios:47a5783646bb3246ceb205',
    messagingSenderId: '978913197408',
    projectId: 'fir-chat-app-aabd2',
    storageBucket: 'fir-chat-app-aabd2.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1CWtH7KxCDdN52dN_NjGiImUZqhVEEUY',
    appId: '1:978913197408:ios:47a5783646bb3246ceb205',
    messagingSenderId: '978913197408',
    projectId: 'fir-chat-app-aabd2',
    storageBucket: 'fir-chat-app-aabd2.appspot.com',
    iosBundleId: 'com.example.chatAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5lo4pAVNEsJdliq5RdFEcMhcLQBCcEA4',
    appId: '1:978913197408:web:000634beb7038dc4ceb205',
    messagingSenderId: '978913197408',
    projectId: 'fir-chat-app-aabd2',
    authDomain: 'fir-chat-app-aabd2.firebaseapp.com',
    storageBucket: 'fir-chat-app-aabd2.appspot.com',
    measurementId: 'G-5VCQ598Z44',
  );
}
